export const languages = [
	{ value: "Afrikaans", label: "Afrikaans", code: "za" },
	{ value: "Albanian", label: "Albanian", code: "al" },
	{ value: "Amharic", label: "Amharic", code: "et" },
	{ value: "Arabic", label: "Arabic", code: "sa" },
	{ value: "Armenian", label: "Armenian", code: "am" },
	{ value: "Azerbaijani", label: "Azerbaijani", code: "az" },
	{ value: "Basque", label: "Basque", code: "es" },
	{ value: "Belarusian", label: "Belarusian", code: "by" },
	{ value: "Bengali", label: "Bengali", code: "bd" },
	{ value: "Bosnian", label: "Bosnian", code: "ba" },
	{ value: "Bulgarian", label: "Bulgarian", code: "bg" },
	{ value: "Catalan", label: "Catalan", code: "es" },
	{ value: "Cebuano", label: "Cebuano", code: "ph" },
	{ value: "Chinese (Simplified)", label: "Chinese (Simplified)", code: "cn" },
	{
		value: "Chinese (Traditional)",
		label: "Chinese (Traditional)",
		code: "tw",
	},
	{ value: "Corsican", label: "Corsican", code: "fr" },
	{ value: "Croatian", label: "Croatian", code: "hr" },
	{ value: "Czech", label: "Czech", code: "cz" },
	{ value: "Danish", label: "Danish", code: "dk" },
	{ value: "Dutch", label: "Dutch", code: "nl" },
	{ value: "English", label: "English", code: "gb" },
	{ value: "Esperanto", label: "Esperanto", code: "eo" },
	{ value: "Estonian", label: "Estonian", code: "ee" },
	{ value: "Filipino", label: "Filipino", code: "ph" },
	{ value: "Finnish", label: "Finnish", code: "fi" },
	{ value: "French", label: "French", code: "fr" },
	{ value: "Frisian", label: "Frisian", code: "nl" },
	{ value: "Galician", label: "Galician", code: "es" },
	{ value: "Georgian", label: "Georgian", code: "ge" },
	{ value: "German", label: "German", code: "de" },
	{ value: "Greek", label: "Greek", code: "gr" },
	{ value: "Gujarati", label: "Gujarati", code: "in" },
	{ value: "Haitian Creole", label: "Haitian Creole", code: "ht" },
	{ value: "Hausa", label: "Hausa", code: "ng" },
	{ value: "Hawaiian", label: "Hawaiian", code: "us" },
	{ value: "Hebrew", label: "Hebrew", code: "il" },
	{ value: "Hindi", label: "Hindi", code: "in" },
	{ value: "Hmong", label: "Hmong", code: "la" },
	{ value: "Hungarian", label: "Hungarian", code: "hu" },
	{ value: "Icelandic", label: "Icelandic", code: "is" },
	{ value: "Igbo", label: "Igbo", code: "ng" },
	{ value: "Indonesian", label: "Indonesian", code: "id" },
	{ value: "Irish", label: "Irish", code: "ie" },
	{ value: "Italian", label: "Italian", code: "it" },
	{ value: "Japanese", label: "Japanese", code: "jp" },
	{ value: "Javanese", label: "Javanese", code: "id" },
	{ value: "Kannada", label: "Kannada", code: "in" },
	{ value: "Kazakh", label: "Kazakh", code: "kz" },
	{ value: "Khmer", label: "Khmer", code: "kh" },
	{ value: "Kinyarwanda", label: "Kinyarwanda", code: "rw" },
	{ value: "Korean", label: "Korean", code: "kr" },
	{ value: "Kurdish", label: "Kurdish", code: "iq" },
	{ value: "Kyrgyz", label: "Kyrgyz", code: "kg" },
	{ value: "Lao", label: "Lao", code: "la" },
	{ value: "Latin", label: "Latin", code: "va" },
	{ value: "Latvian", label: "Latvian", code: "lv" },
	{ value: "Lithuanian", label: "Lithuanian", code: "lt" },
	{ value: "Luxembourgish", label: "Luxembourgish", code: "lu" },
	{ value: "Macedonian", label: "Macedonian", code: "mk" },
	{ value: "Malagasy", label: "Malagasy", code: "mg" },
	{ value: "Malay", label: "Malay", code: "my" },
	{ value: "Malayalam", label: "Malayalam", code: "in" },
	{ value: "Maltese", label: "Maltese", code: "mt" },
	{ value: "Maori", label: "Maori", code: "nz" },
	{ value: "Marathi", label: "Marathi", code: "in" },
	{ value: "Mongolian", label: "Mongolian", code: "mn" },
	{ value: "Myanmar (Burmese)", label: "Myanmar (Burmese)", code: "mm" },
	{ value: "Nepali", label: "Nepali", code: "np" },
	{ value: "Norwegian", label: "Norwegian", code: "no" },
	{ value: "Nyanja (Chichewa)", label: "Nyanja (Chichewa)", code: "mw" },
	{ value: "Odia (Oriya)", label: "Odia (Oriya)", code: "in" },
	{ value: "Pashto", label: "Pashto", code: "af" },
	{ value: "Persian", label: "Persian", code: "ir" },
	{ value: "Polish", label: "Polish", code: "pl" },
	{ value: "Portuguese", label: "Portuguese", code: "pt" },
	{ value: "Punjabi", label: "Punjabi", code: "in" },
	{ value: "Romanian", label: "Romanian", code: "ro" },
	{ value: "Russian", label: "Russian", code: "ru" },
	{ value: "Samoan", label: "Samoan", code: "ws" },
	{ value: "Scots Gaelic", label: "Scots Gaelic", code: "gb-sct" },
	{ value: "Serbian", label: "Serbian", code: "rs" },
	{ value: "Sesotho", label: "Sesotho", code: "ls" },
	{ value: "Shona", label: "Shona", code: "zw" },
	{ value: "Sindhi", label: "Sindhi", code: "pk" },
	{ value: "Sinhala (Sinhalese)", label: "Sinhala (Sinhalese)", code: "lk" },
	{ value: "Slovak", label: "Slovak", code: "sk" },
	{ value: "Slovenian", label: "Slovenian", code: "si" },
	{ value: "Somali", label: "Somali", code: "so" },
	{ value: "Spanish", label: "Spanish", code: "es" },
	{ value: "Sundanese", label: "Sundanese", code: "id" },
	{ value: "Swahili", label: "Swahili", code: "ke" },
	{ value: "Swedish", label: "Swedish", code: "se" },
	{ value: "Tajik", label: "Tajik", code: "tj" },
	{ value: "Tamil", label: "Tamil", code: "lk" },
	{ value: "Tatar", label: "Tatar", code: "ru" },
	{ value: "Telugu", label: "Telugu", code: "in" },
	{ value: "Thai", label: "Thai", code: "th" },
	{ value: "Turkish", label: "Turkish", code: "tr" },
	{ value: "Turkmen", label: "Turkmen", code: "tm" },
	{ value: "Ukrainian", label: "Ukrainian", code: "ua" },
	{ value: "Urdu", label: "Urdu", code: "pk" },
	{ value: "Uyghur", label: "Uyghur", code: "cn" },
	{ value: "Uzbek", label: "Uzbek", code: "uz" },
	{ value: "Vietnamese", label: "Vietnamese", code: "vn" },
	{ value: "Welsh", label: "Welsh", code: "gb-wls" },
	{ value: "Xhosa", label: "Xhosa", code: "za" },
	{ value: "Yiddish", label: "Yiddish", code: "il" },
	{ value: "Yoruba", label: "Yoruba", code: "ng" },
	{ value: "Zulu", label: "Zulu", code: "za" },
];

const languageMap = new Map(
	languages.map((lang) => [lang.value.toLowerCase(), lang.code])
);

export const getLanguageCode = (languageName) => {
	if (!languageName) return "xx";
	return languageMap.get(languageName.toLowerCase()) || "xx";
};
